name: 'Latest'

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Install dependencies
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 20F802FE798E6857
          sudo add-apt-repository "deb https://www.itforarchivists.com/ buster main"
          sudo apt-get -qq update
          sudo apt-get -qq install siegfried -y
          sudo cp .github/workflows/bin/clamscan /usr/bin/clamscan
          sudo cp .github/workflows/bin/clamscan /usr/bin/clamdscan
          sudo chmod a+rx /usr/bin/clamscan /usr/bin/clamdscan
      - name: Run tests & install
        run:
          mvn $MAVEN_CLI_OPTS -Dtestng.groups="travis" -Proda-wui-docker -Denforcer.skip=true clean org.jacoco:jacoco-maven-plugin:prepare-agent install
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Deploy to DockerHub
        run: |
          docker push keeps/roda:latest
      - name: Trigger KEEPS GitLab CI/CD
        uses: appleboy/gitlab-ci-action@master
        with:
          host: ${{ secrets.GITLAB_RODA_DEV_TRIGGER }}
          token: ${{ secrets.GITLAB_RODA_DEV_TRIGGER_TOKEN }}
          project_id: ${{ secrets.GITLAB_RODA_PROJECT_ID }}
          ref: 'master'
